apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: nginx-demo-nodeport-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30180
    name: http
  selector:
    name: jenkins